name: Autotest

on:
  pull_request:
    branches: [ main ]

jobs:
  autotests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: |
        npm ci

    - name: Lint
      run: |
        npm run lint

    - name: Test
      run: |
        npm run test

    - name: Build
      run: |
        npm run build
